package entities;
// Generated 2017-10-02 19:26:42 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassScheduleId generated by hbm2java
 * It's a view from Database!
 */
@Embeddable
public class ClassScheduleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8820616193113958309L;
	private String name;
	private Date date;
	private String day;
	private Date scheduledTime;
	private String trainerName;
	private String trainerLastName;

	public ClassScheduleId() {
	}

	public ClassScheduleId(String name, String trainerName, String trainerLastName) {
		this.name = name;
		this.trainerName = trainerName;
		this.trainerLastName = trainerLastName;
	}

	public ClassScheduleId(String name, Date date, String day, Date scheduledTime, String trainerName,
			String trainerLastName) {
		this.name = name;
		this.date = date;
		this.day = day;
		this.scheduledTime = scheduledTime;
		this.trainerName = trainerName;
		this.trainerLastName = trainerLastName;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Day", length = 9)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "Scheduled time", length = 8)
	public Date getScheduledTime() {
		return this.scheduledTime;
	}

	public void setScheduledTime(Date scheduledTime) {
		this.scheduledTime = scheduledTime;
	}

	@Column(name = "Trainer name", nullable = false, length = 20)
	public String getTrainerName() {
		return this.trainerName;
	}

	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName;
	}

	@Column(name = "Trainer last name", nullable = false, length = 40)
	public String getTrainerLastName() {
		return this.trainerLastName;
	}

	public void setTrainerLastName(String trainerLastName) {
		this.trainerLastName = trainerLastName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassScheduleId))
			return false;
		ClassScheduleId castOther = (ClassScheduleId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getDay() == castOther.getDay()) || (this.getDay() != null && castOther.getDay() != null
						&& this.getDay().equals(castOther.getDay())))
				&& ((this.getScheduledTime() == castOther.getScheduledTime())
						|| (this.getScheduledTime() != null && castOther.getScheduledTime() != null
								&& this.getScheduledTime().equals(castOther.getScheduledTime())))
				&& ((this.getTrainerName() == castOther.getTrainerName())
						|| (this.getTrainerName() != null && castOther.getTrainerName() != null
								&& this.getTrainerName().equals(castOther.getTrainerName())))
				&& ((this.getTrainerLastName() == castOther.getTrainerLastName())
						|| (this.getTrainerLastName() != null && castOther.getTrainerLastName() != null
								&& this.getTrainerLastName().equals(castOther.getTrainerLastName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getDay() == null ? 0 : this.getDay().hashCode());
		result = 37 * result + (getScheduledTime() == null ? 0 : this.getScheduledTime().hashCode());
		result = 37 * result + (getTrainerName() == null ? 0 : this.getTrainerName().hashCode());
		result = 37 * result + (getTrainerLastName() == null ? 0 : this.getTrainerLastName().hashCode());
		return result;
	}

}
