package entities;
// Generated 2017-10-02 19:26:42 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClassSchedule generated by hbm2java
 */
@Entity
@Table(name = "class_schedule", catalog = "simplegymdb")
public class ClassSchedule implements java.io.Serializable {

	private ClassScheduleId id;

	public ClassSchedule() {
	}

	public ClassSchedule(ClassScheduleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "name", column = @Column(name = "Name", nullable = false, length = 50)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", length = 10)),
			@AttributeOverride(name = "day", column = @Column(name = "Day", length = 9)),
			@AttributeOverride(name = "scheduledTime", column = @Column(name = "Scheduled time", length = 8)),
			@AttributeOverride(name = "trainerName", column = @Column(name = "Trainer name", nullable = false, length = 20)),
			@AttributeOverride(name = "trainerLastName", column = @Column(name = "Trainer last name", nullable = false, length = 40)) })
	public ClassScheduleId getId() {
		return this.id;
	}

	public void setId(ClassScheduleId id) {
		this.id = id;
	}

}
